#Generated Form Function
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 25.10.2021 16:50
    # Generated By: Robin
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $whole_form = New-Object System.Windows.Forms.Form
    $Lbl_welcome = New-Object System.Windows.Forms.Label
    $Btn_delete = New-Object System.Windows.Forms.Button
    $Btn_backup_path = New-Object System.Windows.Forms.Button
    $Btn_original_path = New-Object System.Windows.Forms.Button
    $Dialog_original_path = New-Object System.Windows.Forms.FolderBrowserDialog    #Open File Explorer and select Folder
    $button_analyzer = New-Object System.Windows.Forms.Button
    $Btn_go = New-Object System.Windows.Forms.Button
    $Lbl_sort = New-Object System.Windows.Forms.Label
    $DD_sort = New-Object System.Windows.Forms.ComboBox
    $Lbl_group_sort = New-Object System.Windows.Forms.Label
    $Clb_content = New-Object System.Windows.Forms.CheckedListBox
    $DD_group_sort = New-Object System.Windows.Forms.ComboBox
    $Lbl_move_path = New-Object System.Windows.Forms.Label
    $Tbox_move_path = New-Object System.Windows.Forms.TextBox
    $Dialog_move_path = New-Object System.Windows.Forms.FolderBrowserDialog    #Open File Explorer and select Folder
    $Rbtn_move = New-Object System.Windows.Forms.RadioButton
    $Rbtn_copy = New-Object System.Windows.Forms.RadioButton
    $Btn_ok_path = New-Object System.Windows.Forms.Button
    $Tbox_original_path = New-Object System.Windows.Forms.TextBox
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.

    $Btn_original_path_Click= 
    {
        #set standard Path for File Dialog
        $Dialog_original_path.SelectedPath = "$env:userprofile\Documents"
                
        #Open Forms with before set default path
        $ok = $Dialog_original_path.ShowDialog()
        if ($ok -eq "OK")
        {
            #Show selected Path in Textbox
            $Tbox_original_path.Text = $Dialog_original_path.SelectedPath #Gibt selektierten Ordner zurück
        }    
    }

    #Action when Dropdown gets selected
    $DD_sort_MouseClick= 
    {
        $DD_Array_Filetyp = "*.txt" , "*.exe" , "*.ps1" , "*.pdf" , "*.docx" , "*.msi" 
        $DD_Array_Owner = "robin" , "robin.admin" , "Admin" , "root"  
            
        #Read from Dropdown
        $group_sort = $DD_group_sort.SelectedItem.ToString()
        if ($group_sort -eq "Filetyp" ) {
            $DD_sort.Items.Clear()
            ForEach ($Item in $DD_Array_Filetyp) {
                $DD_sort.Items.Add($Item) | Out-Null
                }
           
        }

        elseif ($group_sort -eq "Owner") {
            $DD_sort.Items.Clear()
            ForEach ($Item in $DD_Array_Owner) {
                $DD_sort.Items.Add($Item) | Out-Null
                }
        }
    }

    $Btn_ok_path_Click= 
    {
        #Refresh Content
        $Clb_content.Items.Clear()

        #Build Path
        $original_path = $($Tbox_original_path.Text) + "\*"

        #read Valuo from Dropdown
        $sort = $DD_sort.SelectedItem.ToString()

        #Get Items 
        Get-Childitem -Path $original_path -Include $sort | Sort-Object -Property Name | ForEach-Object{$Clb_content.Items.Add($_.name)}
    }

    $Btn_delete_Click= 
    {
        Set-Location $original_path
        #Loop through all Checked Items and remove them
        foreach ($item in $Clb_content.CheckedItems) {
            write-host $item
            remove-item $item
        }

        #Funktion erstellen
        $Clb_content.Items.Clear()
        #Get Items 
        Get-Childitem -Path $original_path -Include $sort | Sort-Object -Property Name | ForEach-Object{$Clb_content.Items.Add($_.name)}
        #Bis Hier
            
    }
    
    $Btn_backup_path_Click= 
    {
        #set standard Path for File Dialog
        $Dialog_move_path.SelectedPath = "$env:userprofile\Documents"
                
        #Open Forms with before set default path
        $ok = $Dialog_move_path.ShowDialog()
        if ($ok -eq "OK")
        {
            #Show selected Path in Textbox
            $Tbox_move_path.Text = $Dialog_move_path.SelectedPath #Gibt selektierten Ordner zurück
        }
    }
    
    $Btn_go_Click= 
    {
        #Pfad auslesen
        $original_path = $($Tbox_original_path.Text)
        $move_path = $Tbox_move_path.Text
        
        if($Rbtn_move.Checked)
        {
                foreach ($item in $Clb_content.CheckedItems)
                {
                    #Build Paths
                    $item_path = $original_path + "/" + $item
                    $move_path = $move_path + "/" + $item

                    #Pfad testen
                    if(!(Test-Path -Path $move_path))
                    {       
                        Move-Item $item_path $move_path
                    }

                    else
                    {
                        write-host "File $item already exists!"
                    }
                }

                #Funktion erstellen
                $Clb_content.Items.Clear()
                Get-Childitem | Sort-Object -Property Name | ForEach-Object{$Clb_content.Items.Add($_.name)}
                #Bis Hier
        }

        elseif ($Rbtn_copy.Checked)
        {            
                foreach ($item in $Clb_content.CheckedItems)
                {
                    #Build Paths
                    $item_path = $original_path + "/" + $item
                    $copy_path = $move_path + "/" + $item

                    #Pfad testen
                    if(!(Test-Path -Path $copy_path ))
                    {
                        Copy-Item $item_path $copy_path
                    }
                    else
                    {
                        write-host "File $item already exists!"
                    }
                }

                #Funktion erstellen
                $Clb_content.Items.Clear()
                Get-Childitem | Sort-Object -Property Name | ForEach-Object{$Clb_content.Items.Add($_.name)}
                #Bis Hier
        }

        else
        {
            write-host "Select an Action!"
        }
    }
    
    $Btn_analyzer_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    
    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $whole_form.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 617
    $System_Drawing_Size.Width = 676
    $whole_form.ClientSize = $System_Drawing_Size
    $whole_form.DataBindings.DefaultDataSourceUpdateMode = 0
    $whole_form.Name = "whole_form"
    $whole_form.Text = "File Sorter"
    
    $Lbl_welcome.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 17
    $System_Drawing_Point.Y = 33
    $Lbl_welcome.Location = $System_Drawing_Point
    $Lbl_welcome.Name = "Lbl_welcome"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 458
    $Lbl_welcome.Size = $System_Drawing_Size
    $Lbl_welcome.TabIndex = 20
    $Lbl_welcome.Text = "With this Tool you can search for Files, sort and move/delete them. Have Fun!"
    
    $whole_form.Controls.Add($Lbl_welcome)
    
    
    $Btn_delete.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 215
    $System_Drawing_Point.Y = 466
    $Btn_delete.Location = $System_Drawing_Point
    $Btn_delete.Name = "Btn_delete"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 162
    $Btn_delete.Size = $System_Drawing_Size
    $Btn_delete.TabIndex = 19
    $Btn_delete.Text = "Delete selected Items"
    $Btn_delete.UseVisualStyleBackColor = $True
    $Btn_delete.add_Click($Btn_delete_Click)
    
    $whole_form.Controls.Add($Btn_delete)
    
    
    $Btn_backup_path.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 360
    $System_Drawing_Point.Y = 511
    $Btn_backup_path.Location = $System_Drawing_Point
    $Btn_backup_path.Name = "Btn_backup_path"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $Btn_backup_path.Size = $System_Drawing_Size
    $Btn_backup_path.TabIndex = 18
    $Btn_backup_path.Text = "..."
    $Btn_backup_path.UseVisualStyleBackColor = $True
    $Btn_backup_path.add_Click($Btn_backup_path_Click)
    
    $whole_form.Controls.Add($Btn_backup_path)
    
    
    $Btn_original_path.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 364
    $System_Drawing_Point.Y = 102
    $Btn_original_path.Location = $System_Drawing_Point
    $Btn_original_path.Name = "Btn_original_path"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $Btn_original_path.Size = $System_Drawing_Size
    $Btn_original_path.TabIndex = 17
    $Btn_original_path.Text = "..."
    $Btn_original_path.UseVisualStyleBackColor = $True
    $Btn_original_path.add_Click($Btn_original_path_Click)
    
    $whole_form.Controls.Add($Btn_original_path)
    
    
    $button_analyzer.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 17
    $System_Drawing_Point.Y = 582
    $button_analyzer.Location = $System_Drawing_Point
    $button_analyzer.Name = "button_analyzer"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $button_analyzer.Size = $System_Drawing_Size
    $button_analyzer.TabIndex = 16
    $button_analyzer.Text = "Analyzer"
    $button_analyzer.UseVisualStyleBackColor = $True
    $button_analyzer.add_Click($Btn_analyzer_Click)
    
    $whole_form.Controls.Add($button_analyzer)
    
    
    $Btn_go.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 572
    $System_Drawing_Point.Y = 582
    $Btn_go.Location = $System_Drawing_Point
    $Btn_go.Name = "Btn_go"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $Btn_go.Size = $System_Drawing_Size
    $Btn_go.TabIndex = 15
    $Btn_go.Text = "Go!"
    $Btn_go.UseVisualStyleBackColor = $True
    $Btn_go.add_Click($Btn_go_Click)
    
    $whole_form.Controls.Add($Btn_go)
    
    $Lbl_sort.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 249
    $System_Drawing_Point.Y = 138
    $Lbl_sort.Location = $System_Drawing_Point
    $Lbl_sort.Name = "Lbl_sort"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 93
    $Lbl_sort.Size = $System_Drawing_Size
    $Lbl_sort.TabIndex = 13
    $Lbl_sort.Text = "Attributes to Sort:"
    $Lbl_sort.TextAlign = 64
    
    $whole_form.Controls.Add($Lbl_sort)
    
   
    $DD_sort.DataBindings.DefaultDataSourceUpdateMode = 0
    $DD_sort.FormattingEnabled = $True
    $DD_sort.Items.Add("*.exe")|Out-Null
    $DD_sort.Items.Add("*.ps1")|Out-Null
    $DD_sort.Items.Add("*.txt")|Out-Null
    $DD_sort.Items.Add("*.pdf")|Out-Null
    $DD_sort.Items.Add("Robin")|Out-Null
    $DD_sort.Items.Add("Admin")|Out-Null
    $DD_sort.Items.Add("Alex")|Out-Null
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 364
    $System_Drawing_Point.Y = 138
    $DD_sort.Location = $System_Drawing_Point
    $DD_sort.Name = "DD_sort"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 72
    $DD_sort.Size = $System_Drawing_Size
    $DD_sort.TabIndex = 12
    $DD_sort.add_MouseClick($DD_sort_MouseClick)
    
    $whole_form.Controls.Add($DD_sort)
    
    $Lbl_group_sort.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 15
    $System_Drawing_Point.Y = 140
    $Lbl_group_sort.Location = $System_Drawing_Point
    $Lbl_group_sort.Name = "Lbl_group_sort"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 127
    $Lbl_group_sort.Size = $System_Drawing_Size
    $Lbl_group_sort.TabIndex = 11
    $Lbl_group_sort.Text = "Attribute Group to Sort:"
    $Lbl_group_sort.TextAlign = 64
    
    $whole_form.Controls.Add($Lbl_group_sort)
    
    $Clb_content.DataBindings.DefaultDataSourceUpdateMode = 0
    $Clb_content.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 15
    $System_Drawing_Point.Y = 177
    $Clb_content.Location = $System_Drawing_Point
    $Clb_content.Name = "Clb_content"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 274
    $System_Drawing_Size.Width = 632
    $Clb_content.Size = $System_Drawing_Size
    $Clb_content.TabIndex = 10
    
    $whole_form.Controls.Add($Clb_content)
    
    $DD_group_sort.DataBindings.DefaultDataSourceUpdateMode = 0
    $DD_group_sort.FormattingEnabled = $True
    $DD_group_sort.Items.Add("Filetyp")|Out-Null
    $DD_group_sort.Items.Add("Owner")|Out-Null
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 148
    $System_Drawing_Point.Y = 140
    $DD_group_sort.Location = $System_Drawing_Point
    $DD_group_sort.Name = "DD_group_sort"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 72
    $DD_group_sort.Size = $System_Drawing_Size
    $DD_group_sort.TabIndex = 9
    
    $whole_form.Controls.Add($DD_group_sort)
    
    $Lbl_move_path.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 15
    $System_Drawing_Point.Y = 512
    $Lbl_move_path.Location = $System_Drawing_Point
    $Lbl_move_path.Name = "Lbl_move_path"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 92
    $Lbl_move_path.Size = $System_Drawing_Size
    $Lbl_move_path.TabIndex = 8
    $Lbl_move_path.Text = "Copy/Move to"
    $Lbl_move_path.TextAlign = 64
    
    $whole_form.Controls.Add($Lbl_move_path)
    
    $Tbox_move_path.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 124
    $System_Drawing_Point.Y = 513
    $Tbox_move_path.Location = $System_Drawing_Point
    $Tbox_move_path.Name = "Tbox_move_path"
    $Tbox_move_path.ReadOnly = $True
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 218
    $Tbox_move_path.Size = $System_Drawing_Size
    $Tbox_move_path.TabIndex = 6
    
    $whole_form.Controls.Add($Tbox_move_path)
    
    
    $Rbtn_move.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 127
    $System_Drawing_Point.Y = 465
    $Rbtn_move.Location = $System_Drawing_Point
    $Rbtn_move.Name = "Rbtn_move"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 104
    $Rbtn_move.Size = $System_Drawing_Size
    $Rbtn_move.TabIndex = 5
    $Rbtn_move.TabStop = $True
    $Rbtn_move.Text = "Move"
    $Rbtn_move.UseVisualStyleBackColor = $True
    
    $whole_form.Controls.Add($Rbtn_move)
    
    
    $Rbtn_copy.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 32
    $System_Drawing_Point.Y = 465
    $Rbtn_copy.Location = $System_Drawing_Point
    $Rbtn_copy.Name = "Rbtn_copy"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 75
    $Rbtn_copy.Size = $System_Drawing_Size
    $Rbtn_copy.TabIndex = 3
    $Rbtn_copy.TabStop = $True
    $Rbtn_copy.Text = "Copy"
    $Rbtn_copy.UseVisualStyleBackColor = $True
    
    $whole_form.Controls.Add($Rbtn_copy)
    
    
    $Btn_ok_path.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 472
    $System_Drawing_Point.Y = 102
    $Btn_ok_path.Location = $System_Drawing_Point
    $Btn_ok_path.Name = "Btn_ok_path"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 67
    $System_Drawing_Size.Width = 85
    $Btn_ok_path.Size = $System_Drawing_Size
    $Btn_ok_path.TabIndex = 1
    $Btn_ok_path.Text = "OK"
    $Btn_ok_path.UseVisualStyleBackColor = $True
    $Btn_ok_path.add_Click($Btn_ok_path_Click)
    
    $whole_form.Controls.Add($Btn_ok_path)
    
    $Tbox_original_path.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 17
    $System_Drawing_Point.Y = 104
    $Tbox_original_path.Location = $System_Drawing_Point
    $Tbox_original_path.Name = "Tbox_original_path"
    $Tbox_original_path.ReadOnly = $True
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 341
    $Tbox_original_path.Size = $System_Drawing_Size
    $Tbox_original_path.TabIndex = 0
    
    $whole_form.Controls.Add($Tbox_original_path)
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $whole_form.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $whole_form.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $whole_form.ShowDialog()| Out-Null
    
    } #End Function
    
    #Call the Function
    GenerateForm
    