#Generated Form Function
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 26.08.2019 14:36
    # Generated By: michael
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $btn_Aktualisieren = New-Object System.Windows.Forms.Button
    $ClistBox1 = New-Object System.Windows.Forms.CheckedListBox
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $btn_Akt_Click= 
    {
     #Listbox löschen und füllen:
     #$ClistBox1.ClearSelected()
     $ClistBox1.Items.Clear()
    
     Get-Process | Sort-Object CPU -descending | foreach {$ClistBox1.Items.add([string]$_.id + "`t" + ("{0:N1}" -f $_.CPU)   + "`t" + $_.Processname)}
    }
    
    $CLB_Click= 
    {
      #Aktion on Click: Checked Items auslesen mit Index ...
      write-host "List checked ... >" 
      foreach ($item in $CListBox1.CheckedItems) {
          write-host $cListBox1.Items.IndexOf($item) $item
      }
    }
    
     
    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 457
    $System_Drawing_Size.Width = 286
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "Textbox vs. Listbox"
    
    
    $btn_Aktualisieren.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 14
    $System_Drawing_Point.Y = 10
    $btn_Aktualisieren.Location = $System_Drawing_Point
    $btn_Aktualisieren.Name = "btn_Aktualisieren"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 19
    $System_Drawing_Size.Width = 256
    $btn_Aktualisieren.Size = $System_Drawing_Size
    $btn_Aktualisieren.TabIndex = 2
    $btn_Aktualisieren.Text = "Aktualisieren"
    $btn_Aktualisieren.UseVisualStyleBackColor = $True
    $btn_Aktualisieren.add_Click($btn_Akt_Click)
    
    $form1.Controls.Add($btn_Aktualisieren)
    
    $ClistBox1.DataBindings.DefaultDataSourceUpdateMode = 0
    $ClistBox1.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 14
    $System_Drawing_Point.Y = 35
    $ClistBox1.Location = $System_Drawing_Point
    $ClistBox1.Name = "listBox1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 386
    $System_Drawing_Size.Width = 257
    $ClistBox1.Size = $System_Drawing_Size
    $ClistBox1.TabIndex = 0
    
    $CListBox1.CheckOnClick = $true
    
    $ClistBox1.Add_Click($CLB_Click)
    
    $form1.Controls.Add($ClistBox1)
    
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form1.ShowDialog()| Out-Null
    
    } #End Function
    
    #Call the Function
    GenerateForm
    