#Generated Form Function
function GenerateForm {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 07.10.2021 16:40
    # Generated By: Robin
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $Btn_sort = New-Object System.Windows.Forms.Button
    $Lbox_show = New-Object System.Windows.Forms.CheckedListBox
    $RBtn_delete = New-Object System.Windows.Forms.RadioButton
    $Rbtn_move = New-Object System.Windows.Forms.RadioButton
    $Rbtn_copy = New-Object System.Windows.Forms.RadioButton
    $Btn_select_path = New-Object System.Windows.Forms.Button
    $Dialog_select_path = New-Object System.Windows.Forms.FolderBrowserDialog  #Open File Explorer and select Folder
    $Tbox_path = New-Object System.Windows.Forms.TextBox
    $Lbl_Path = New-Object System.Windows.Forms.Label
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $handler_Btn_sort_Click= 
    {
        Set-Location C:\Users\Robin\Desktop\Sort_this
    
    
        Get-Childitem -Depth 1 | Sort-Object -Property Length | ForEach-Object{$Lbox_show.Items.Add($_.name)}
    

        #Get-Process | %{$item = $Lbox_show.Items.Add($_.processname);$item.SubItems.Add($_.Handles)}
    }
    
    $handler_Rbtn_move_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_Rbtn_copy_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    $handler_Btn_select_path_Click= 
    {
        #set standard Path for File Dialog
        $Dialog_select_path.SelectedPath = "$env:userprofile\Documents"
            
        #Open Forms with before set default path
        $ok = $Dialog_select_path.ShowDialog()
        if ($ok -eq "OK")
        {
            #Show selected Path in Textbox
            $Tbox_path.Text = $Dialog_select_path.SelectedPath #Gibt selektierten Ordner zurück
        }
    
    }
    
    $handler_RBtn_delete_Click= 
    {
    #TODO: Place custom script here
    
    }
    
    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 433
    $System_Drawing_Size.Width = 528
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "Primal Form"
    
    
    $Btn_sort.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 333
    $System_Drawing_Point.Y = 40
    $Btn_sort.Location = $System_Drawing_Point
    $Btn_sort.Name = "Btn_sort"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $Btn_sort.Size = $System_Drawing_Size
    $Btn_sort.TabIndex = 7
    $Btn_sort.Text = "OK"
    $Btn_sort.UseVisualStyleBackColor = $True
    $Btn_sort.add_Click($handler_Btn_sort_Click)
    
    $form1.Controls.Add($Btn_sort)
    
    $Lbox_show.DataBindings.DefaultDataSourceUpdateMode = 0
    $Lbox_show.FormattingEnabled = $True
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 91
    $Lbox_show.Location = $System_Drawing_Point
    $Lbox_show.Name = "Lbox_show"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 184
    $System_Drawing_Size.Width = 490
    $Lbox_show.Size = $System_Drawing_Size
    $Lbox_show.TabIndex = 6
    
    $form1.Controls.Add($Lbox_show)
    
    
    $RBtn_delete.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 26
    $System_Drawing_Point.Y = 350
    $RBtn_delete.Location = $System_Drawing_Point
    $RBtn_delete.Name = "RBtn_delete"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 104
    $RBtn_delete.Size = $System_Drawing_Size
    $RBtn_delete.TabIndex = 5
    $RBtn_delete.TabStop = $True
    $RBtn_delete.Text = "Delete"
    $RBtn_delete.UseVisualStyleBackColor = $True
    $RBtn_delete.add_Click($handler_RBtn_delete_Click)
    
    $form1.Controls.Add($RBtn_delete)
    
    
    $Rbtn_move.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 26
    $System_Drawing_Point.Y = 320
    $Rbtn_move.Location = $System_Drawing_Point
    $Rbtn_move.Name = "Rbtn_move"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 104
    $Rbtn_move.Size = $System_Drawing_Size
    $Rbtn_move.TabIndex = 4
    $Rbtn_move.TabStop = $True
    $Rbtn_move.Text = "Move"
    $Rbtn_move.UseVisualStyleBackColor = $True
    $Rbtn_move.add_Click($handler_Rbtn_move_Click)
    
    $form1.Controls.Add($Rbtn_move)
    
    
    $Rbtn_copy.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 26
    $System_Drawing_Point.Y = 290
    $Rbtn_copy.Location = $System_Drawing_Point
    $Rbtn_copy.Name = "Rbtn_copy"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 112
    $Rbtn_copy.Size = $System_Drawing_Size
    $Rbtn_copy.TabIndex = 3
    $Rbtn_copy.TabStop = $True
    $Rbtn_copy.Text = "Copy"
    $Rbtn_copy.UseVisualStyleBackColor = $True
    $Rbtn_copy.add_Click($handler_Rbtn_copy_Click)
    
    $form1.Controls.Add($Rbtn_copy)
    
    
    $Btn_select_path.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 238
    $System_Drawing_Point.Y = 40
    $Btn_select_path.Location = $System_Drawing_Point
    $Btn_select_path.Name = "Btn_select_path"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $Btn_select_path.Size = $System_Drawing_Size
    $Btn_select_path.TabIndex = 2
    $Btn_select_path.Text = "..."
    $Btn_select_path.UseVisualStyleBackColor = $True
    $Btn_select_path.add_Click($handler_Btn_select_path_Click)
    
    $form1.Controls.Add($Btn_select_path)
    
    $Tbox_path.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 26
    $System_Drawing_Point.Y = 40
    $Tbox_path.Location = $System_Drawing_Point
    $Tbox_path.Name = "Tbox_path"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 205
    $Tbox_path.Size = $System_Drawing_Size
    $Tbox_path.TabIndex = 1
    $Tbox_path.Text = "Select Path ..."
    
    $form1.Controls.Add($Tbox_path)
    
    $Lbl_Path.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 26
    $System_Drawing_Point.Y = 13
    $Lbl_Path.Location = $System_Drawing_Point
    $Lbl_Path.Name = "Lbl_Path"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 300
    $Lbl_Path.Size = $System_Drawing_Size
    $Lbl_Path.TabIndex = 0
    $Lbl_Path.Text = "Select Path to Directory"
    
    $form1.Controls.Add($Lbl_Path)
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form1.ShowDialog()| Out-Null
    
    } #End Function
    
    #Call the Function
    GenerateForm
    